version: '3.9'
services:
  cms-webapp:
    build: .
    container_name: micro-cms-webapp
    ports:
      - 5173:5173
    volumes:
      - .:/usr/src/micro-cms
    command: sh -c "npm i && npm run dev -- --host"
  cms-webapp-docs:
    build: .
    container_name: micro-cms-webapp-docs
    ports:
      - 6006:6006
    volumes:
      - .:/usr/src/micro-cms
    links:
      - cms-webapp
    depends_on:
      - cms-webapp
    command: sh -c "/wait; npm run storybook"
    environment:
      - WAIT_HOSTS=cms-webapp:5173
      - WAIT_HOSTS_TIMEOUT=600
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=15
